### ISSUE TITLE
4.4.0 - Cannot find '../xeroClient.js'

### ISSUE THREAD

**Issue by sandorvasas** [XeroAPI/xero-node#371]
error coming from node_modules/xero-node with node 13.7

shouldn't it be '../XeroClient.js' with a capital X?

```
Error: Cannot find module '../xeroClient'
Require stack:
- PROJECT/server/node_modules/xero-node/dist/gen/api.js
- PROJECT/server/node_modules/xero-node/dist/XeroClient.js
- PROJECT/server/node_modules/xero-node/dist/index.js
- PROJECT/server/src/services/XeroService.ts
- PROJECT/server/src/services/JobService.ts
- PROJECT/server/src/rest-api/Api.ts
- PROJECT/server/src/main.ts
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._resolveFilename (PROJECT/server/node_modules/tsconfig-paths/lib/register.js:75:40)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (PROJECT/server/node_modules/xero-node/dist/gen/api.js:9:10)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (PROJECT/server/node_modules/xero-node/dist/XeroClient.js:20:27)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
[nodemon] app crashed - waiting for file changes before starting...
```

Edit: Definitely a typo. Changed the line in subject to `__export(require("../XeroClient"));` and it works. Please fix.

**Comment by ordapadstar** [comment]
Same issue seen with Node 12.x on AWS Lambda. Works fine in local debug.
Just refactored to use latest XeroClient after the clean-up of 4.2.0. The require line worked on 4.2.0.

The docs don't show the require() line, but I can 

Have tried 
const xeroNode = require('xero-node');
and 
var xeroNode = require('xero-node');

const xeroConfig = {
	clientId: xeroConsumerKey,
	clientSecret: xeroSecretKey,
	redirectUris: [callbackUrl],
	scopes: 'openid profile email accounting.transactions accounting.settings offline_access'.split(" ")
};
let xeroClient = new **xeroNode.**XeroClient(xeroConfig);

**Comment by sandorvasas** [comment]
@ordapadstar That doesn't really sound like the same issue. Probably better to open another thread for that.

**Comment by ordapadstar** [comment]
@sandorvasas  I believe it is the same root issue. 
We get the same error since 4.4.0:

{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module '../xeroClient'\nRequire stack:\n- /var/task/node_modules/xero-node/dist/gen/api.js\n- /var/task/node_modules/xero-node/dist/XeroClient.js\n- /var/task/node_modules/xero-node/dist/index.js\n- /var/task/index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module '../xeroClient'",
        "Require stack:",
        "- /var/task/node_modules/xero-node/dist/gen/api.js",
        "- /var/task/node_modules/xero-node/dist/XeroClient.js",
        "- /var/task/node_modules/xero-node/dist/index.js",
        "- /var/task/index.js",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/index.js",
        "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:955:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)",
        "    at Module.load (internal/modules/cjs/loader.js:811:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:723:14)",
        "    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)",
        "    at internal/main/run_main_module.js:17:11"
    ]
}

**Comment by sandorvasas** [comment]
I see! Indeed it is.

**Comment by SerKnight** [comment]
Hey all - I recall something around this during a fix we did to setup the CI. Will fix in the next couple of hours.

**Comment by SerKnight** [comment]
Hey @sandorvasas & @ordapadstar  - 4.4.1 has that type fixed. Thanks for reporting. Ping us back here with any other issues.

**Comment by ordapadstar** [comment]
> Hey @sandorvasas & @ordapadstar - 4.4.1 has that type fixed. Thanks for reporting. Ping us back here with any other issues.

Thanks you @SerKnight for that fix - it works 👍
